## Tensorflow + RNN 을 활용한 영화 리뷰 감성 분석


#### (1) 데이터 및 필요 라이브러리 설치

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
! wget --no-check-certificate https://raw.github.com/SOMJANG/Mecab-ko-for-Google-Colab/master/install_mecab-ko_on_colab190912.sh

--2019-11-12 16:05:45--  https://raw.github.com/SOMJANG/Mecab-ko-for-Google-Colab/master/install_mecab-ko_on_colab190912.sh
Resolving raw.github.com (raw.github.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.github.com (raw.github.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/SOMJANG/Mecab-ko-for-Google-Colab/master/install_mecab-ko_on_colab190912.sh [following]
--2019-11-12 16:05:45--  https://raw.githubusercontent.com/SOMJANG/Mecab-ko-for-Google-Colab/master/install_mecab-ko_on_colab190912.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2155 (2.1K) [text/plain]
Saving to: ‘install_mecab-ko_on_colab190912.sh’

install_mecab-ko_on 10

In [3]:
!bash install_mecab-ko_on_colab190912.sh

Installing konlpy.....
     |████████████████████████████████| 19.4MB 403kB/s 
     |████████████████████████████████| 2.7MB 31.7MB/s 
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2019-11-12 16:05:52--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 18.205.93.1, 18.205.93.0, 18.205.93.2, ...
Connecting to bitbucket.org (bitbucket.org)|18.205.93.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?Signature=gdx1rKgjFDFvJgdxQxTv1IGMJh0%3D&Expires=1573575818&AWSAccessKeyId=AKIAIQWXW6WLXMB5QZAQ&versionId=null&response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22 [following]
--2019-11-12 16:05:52--  https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-k

In [4]:
!wget --no-check-certificate https://raw.github.com/e9t/nsmc/master/ratings_train.txt

--2019-11-12 16:11:11--  https://raw.github.com/e9t/nsmc/master/ratings_train.txt
Resolving raw.github.com (raw.github.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.github.com (raw.github.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt [following]
--2019-11-12 16:11:11--  https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14628807 (14M) [text/plain]
Saving to: ‘ratings_train.txt’

ratings_train.txt   100%[===================>]  13.95M  --.-KB/s    in 0.1s    

2019-11-12 16:11:11 (93.3 MB/s) - ‘ratings_train.txt’ saved [14628807/14628807]



In [5]:
!wget --no-check-certificate https://raw.github.com/e9t/nsmc/master/ratings_test.txt

--2019-11-12 16:11:14--  https://raw.github.com/e9t/nsmc/master/ratings_test.txt
Resolving raw.github.com (raw.github.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.github.com (raw.github.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt [following]
--2019-11-12 16:11:14--  https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4893335 (4.7M) [text/plain]
Saving to: ‘ratings_test.txt’

ratings_test.txt    100%[===================>]   4.67M  --.-KB/s    in 0.1s    

2019-11-12 16:11:14 (42.0 MB/s) - ‘ratings_test.txt’ saved [4893335/4893335]



In [6]:
# 현재 working directory 확인
import os
os.getcwd()

'/content'

#### (2) 데이터 로드

In [0]:
import pandas as pd

train_data = pd.read_csv("./ratings_train.txt", sep="\t")
test_data = pd.read_csv("./ratings_test.txt", sep="\t")

In [8]:
train_data.isnull().any()

id          False
document     True
label       False
dtype: bool

In [9]:
test_data.isnull().any()

id          False
document     True
label       False
dtype: bool

In [0]:
train_data = train_data.dropna(axis=0)
test_data = test_data.dropna(axis=0)

In [11]:
test_data.head()

id                                           document  label
0  6270596                                                굳 ㅋ      1
1  9274899                               GDNTOPCLASSINTHECLUB      0
2  8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3  6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4  6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0

In [12]:
len(train_data)

149995

In [13]:
len(test_data)

49997

#### (3) 데이터 전처리

#### -- (i) document, label 분리

In [0]:
train_docs = train_data["document"]
train_labels = train_data["label"]

test_docs = test_data["document"]
test_labels = test_data["label"]

#### -- (ii) 형태소 단위로 분리하여 토큰화

In [15]:
# tokenizer 정의
from konlpy.tag import Mecab
mecab = Mecab()
    
# tokenizer 적용 예시
mecab.pos(train_docs[0])

[('아', 'IC'),
 ('더', 'MAG'),
 ('빙', 'MAG'),
 ('.', 'SF'),
 ('.', 'SY'),
 ('진짜', 'MAG'),
 ('짜증', 'NNG'),
 ('나', 'NP'),
 ('네요', 'VCP+EC'),
 ('목소리', 'NNG')]

In [16]:
# 각 문장에 사용된 모든 단어를 아래와 같이 단어/품사 형태로 변환
list(map(lambda x: x[0]+"/"+x[1], mecab.pos(train_docs[0])))

['아/IC',
 '더/MAG',
 '빙/MAG',
 './SF',
 './SY',
 '진짜/MAG',
 '짜증/NNG',
 '나/NP',
 '네요/VCP+EC',
 '목소리/NNG']

In [17]:
from tqdm import tqdm_notebook
train_sents = []
test_sents = []

for sent in tqdm_notebook(train_docs):
  tmp = mecab.pos(sent)
  tmp = list(map(lambda x: x[0]+"/"+x[1], tmp))
  train_sents.append(tmp)

for sent in tqdm_notebook(test_docs):
  tmp = mecab.pos(sent)
  tmp = list(map(lambda x: x[0]+"/"+x[1], tmp))
  test_sents.append(tmp)

In [18]:
train_sents[0]

['아/IC',
 '더/MAG',
 '빙/MAG',
 './SF',
 './SY',
 '진짜/MAG',
 '짜증/NNG',
 '나/NP',
 '네요/VCP+EC',
 '목소리/NNG']

#### -- (iii) word2vec 구축

In [19]:
from gensim.models import Word2Vec

embedding_size = 100
w2v_model = Word2Vec(train_sents, size=embedding_size, window=5, min_count=1, workers=4)
w2v_model.save("w2v.model")

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [20]:
w2v_model["짜증/NNG"]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.780636  , -0.3520033 , -0.4383814 ,  0.8504519 , -0.81522745,
        1.3605123 , -0.38403842,  2.1238668 ,  1.2895788 , -2.723505  ,
       -2.7932317 ,  1.1574689 ,  1.1347818 , -0.54665005,  0.49801293,
        0.4895658 , -0.11378888, -0.6674442 ,  1.379993  ,  0.37373355,
       -1.093418  , -0.5832148 ,  1.8787134 , -0.8983976 , -0.20771725,
        0.49579334, -2.6692386 ,  0.05809939,  0.6464536 ,  2.8460867 ,
        2.3851078 ,  1.6578279 ,  0.7254095 ,  1.828247  ,  0.67153805,
        0.8227378 ,  0.3799414 , -0.31575957, -1.0978452 , -0.3098977 ,
        0.05068572,  1.9338135 ,  1.7728605 ,  2.7912161 , -1.9632813 ,
        1.2875131 , -1.2082504 ,  1.6932997 , -1.0397187 ,  0.16926192,
       -0.5484738 ,  0.67955405,  2.3562806 ,  3.638602  , -1.8735794 ,
       -0.29482886, -0.01295733, -1.3494517 , -1.7647429 , -2.864596  ,
        4.999609  ,  0.7699423 ,  0.8622695 , -0.81426483, -0.32370982,
       -0.6831018 ,  0.35985488, -2.0073984 , -1.6640646 , -0.28

In [21]:
w2v_model.most_similar("짜증/NNG")

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('승질/NNG', 0.7194774150848389),
 ('실감/NNG', 0.6722358465194702),
 ('티/NNG', 0.651922881603241),
 ('화딱지/NNG', 0.6351636648178101),
 ('신물/NNG', 0.6269192099571228),
 ('진절머리/NNG', 0.6191627979278564),
 ('끝/NNG', 0.6160387992858887),
 ('화/NNG', 0.5940001606941223),
 ('퇘/UNKNOWN', 0.5853357315063477),
 ('머리털/NNG', 0.5815408229827881)]

In [0]:
# special token 정의
word2idx = {"<PAD>":0, "<UNK>":1}
vocab = list(w2v_model.wv.vocab.keys())

for word in vocab:
  word2idx[word] = len(word2idx)

In [23]:
word2idx

{'<PAD>': 0,
 '<UNK>': 1,
 '아/IC': 2,
 '더/MAG': 3,
 '빙/MAG': 4,
 './SF': 5,
 './SY': 6,
 '진짜/MAG': 7,
 '짜증/NNG': 8,
 '나/NP': 9,
 '네요/VCP+EC': 10,
 '목소리/NNG': 11,
 '흠/IC': 12,
 '../SY': 13,
 '포스터/NNP': 14,
 '보고/JKB': 15,
 '초딩/NNG': 16,
 '영화/NNG': 17,
 '줄/NNG': 18,
 '.../SY': 19,
 '오버/NNG': 20,
 '연기/NNG': 21,
 '조차/JX': 22,
 '가볍/VA': 23,
 '지/EC': 24,
 '않/VX': 25,
 '구나/EC': 26,
 '너무/MAG': 27,
 '재/XPN': 28,
 '밓었다그래서보는것을추천한다/UNKNOWN': 29,
 '교도소/NNG': 30,
 '이야기/NNG': 31,
 '구먼/VCP+EF': 32,
 '솔직히/MAG': 33,
 '재미/NNG': 34,
 '는/JX': 35,
 '없/VA': 36,
 '다/EF': 37,
 '평점/NNG': 38,
 '조정/NNG': 39,
 '사이몬페그/NNP': 40,
 '의/JKG': 41,
 '익살/NNG': 42,
 '스런/XSA+ETM': 43,
 '가/JKS': 44,
 '돋보였/VV+EP': 45,
 '던/ETM': 46,
 '!/SY': 47,
 '스파이더맨/NNP': 48,
 '에서/JKB': 49,
 '늙/VV': 50,
 '어/EC': 51,
 '보이/VV': 52,
 '기/ETN': 53,
 '만/JX': 54,
 '했/VV+EP': 55,
 '커스틴/NNP': 56,
 '던스트/NNP': 57,
 '너무나/MAG': 58,
 '도/JX': 59,
 '이뻐/VA+EC': 60,
 '보였/VV+EP': 61,
 '다/EC': 62,
 '막/MAJ': 63,
 '걸음마/NNG': 64,
 '뗀/VV+ETM': 65,
 '3/SN': 66,
 '세/

In [0]:
import numpy as np

embedding_matrix = []
unique_words = list(word2idx.keys())
for i in range(0, len(word2idx)):
  # special token 의 embedding vector 는 zero vector 로 처리
  if i == 0 or i == 1:
    embedding_matrix.append(np.zeros(embedding_size, dtype="float32"))
  else:
    embedding_matrix.append(w2v_model.wv.__getitem__(unique_words[i]))

embedding_matrix = np.stack(embedding_matrix)

In [25]:
embedding_matrix.shape

(61251, 100)

In [26]:
embedding_matrix[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [27]:
embedding_matrix[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [28]:
embedding_matrix[2]

array([ 1.5601265 , -1.0389614 ,  0.3894166 , -1.0632013 ,  0.34987882,
       -0.52913564,  1.0757109 ,  1.9376307 ,  0.85776925, -0.8744817 ,
       -3.284188  ,  0.28594792,  0.6986234 ,  0.2937764 , -0.35262805,
        2.181345  ,  0.2454446 ,  0.53284854, -0.43141425,  2.14179   ,
       -0.34718823,  0.31175902, -0.26613152, -0.8910395 ,  1.2828112 ,
        2.5179443 , -1.7329285 ,  1.0823628 ,  1.0411897 ,  1.9695662 ,
       -0.03211784,  1.6453905 ,  0.8338007 ,  0.49949476,  1.1901419 ,
       -0.8479583 , -1.7027003 , -0.9391094 , -0.23602954, -0.14107573,
       -0.35924008,  0.8370193 ,  0.72356343,  0.75955606, -0.32882813,
       -2.1985795 ,  0.3078943 , -0.58603066,  0.3646786 ,  0.9072294 ,
       -0.8110098 ,  1.1701301 ,  0.18733183,  0.49740446,  0.6796976 ,
       -0.03538955,  0.57373375, -3.2236524 , -0.04201769,  0.4157925 ,
        0.7189048 ,  1.0762743 ,  0.71218157, -0.15299736, -0.14189926,
        0.42118958,  0.29934648, -1.4957427 , -0.110461  , -0.43

####-- (iv) 전처리 결과 저장

In [0]:
import pickle

save_data = {
    "word2idx": word2idx,
    "embedding_matrix": embedding_matrix,
    "train_sents": train_sents,
    "test_sents": test_sents,
    "train_labels": train_labels,
    "test_labels": test_labels
}

with open("./drive/My Drive/Colab Notebooks/preprocessed_data.pkl", "wb") as f:
  pickle.dump(save_data, f)

#### (4) Embedding Lookup 예시

In [30]:
import tensorflow as tf
tf.enable_eager_execution()
from tensorflow.keras.initializers import Constant
tf.__version__

'1.15.0'

In [0]:
vocab_size = len(word2idx)
embedding_layer = tf.keras.layers.Embedding(
    input_dim = vocab_size,
    output_dim = embedding_size,
    embeddings_initializer = Constant(embedding_matrix),
    trainable = False
)

In [32]:
result = embedding_layer(tf.constant([0,1,2]))
result.numpy()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 