In [13]:
import torch, torch.utils.data, torch.nn as nn, torch.optim as optim



In [14]:
def weight_init(m):
    
    if m.__class__.__name__.find('Linear') != -1 :
        m.weight.data.uniform_(0.0, 1.0)
        m.bias.data.fill_(0)


In [19]:
class xor_dataloader(torch.utils.data.Dataset):
    
    def __init__(self):
        super().__init__()
        self.input = torch.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]])
        self.target = torch.Tensor([[0], [1], [1], [1], [0]])
        
    def __len__(self) -> int:
        
        return len(self.input)
    
    def __getitem__(self, item):
        
        
        X = self.input[item]
        t = self.target[item]
        
        return X, t

In [23]:
class TwoLayerNetVerPyTorch(nn.Module):
    
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        self.network1 = nn.Sequential(
            nn.Linear(self.input_size, self.hidden_size),
            nn.Sigmoid(),
            nn.Linear(self.hidden_size, self.output_size),
            nn.Sigmoid(),
        )
    def forward(self, x):
        return self.network1(x)


In [24]:
epochs = 20000
learning_rate = 0.1

net= TwoLayerNetVerPyTorch(2, 3, 1)
net.apply(weight_init)
optimizer = optim.SGD(net.parameters(), lr=learning_rate)
dataloader = torch.utils.data.DataLoader(xor_dataloader(), batch_size=4)

MSE = nn.MSELoss()



In [26]:
train_loss_list = []
for i in range(epochs):
    for i, (X, t) in enumerate(dataloader, 0):
        Y = net(X)
        loss = MSE(Y, t)
        
        train_loss_list.append(loss)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        

In [27]:
print("Input is\n", X)

print("Expected output is\n", t)

print("Actual output is\n", Y)





Input is
 tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
Expected output is
 tensor([[0.],
        [1.],
        [1.],
        [1.]])
Actual output is
 tensor([[0.0413],
        [0.9772],
        [0.9778],
        [0.9966]], grad_fn=<SigmoidBackward>)
